### ISSUE TITLE
슬라이드 공유는 어디로?

### ISSUE THREAD

**Issue by kh-kim** [deeplearningzerotoall/PyTorch#11]
PDF 파일의 경우에는 여기에 올리고 GIT-LFS 로 tracking 하면 어떤가요?

**Comment by simonjisu** [comment]
https://drive.google.com/drive/u/0/folders/1x5G-iYpQFIKZTCNc6XL3hNL4Oe_-iBCZ
슬라이드 공유는 여기인데요, 구글프레젠테이션으로 같이 통일해서 하기로 했는데 혹시 위 링크에다 올려주실수 있나요?

**Comment by simonjisu** [comment]
@kh-kim  영상도 같이 올려주시면 됩니다.

**Comment by simonjisu** [comment]
그리고 슬라이드 템플릿 따로 만들었었는데 .. ㅠㅠ 한번 봐주시고 최대한 비슷하게 맞춰주세용 ㅋㅋ 아무래도 여러사람이 하게 되면 통일성이 좀 떨어질것 같아서요 
https://docs.google.com/presentation/d/16I9zqH9naFgNS1lXS9cR5PfrXfHZySSk0q9u8tR4ebQ/edit?usp=sharing

**Comment by simonjisu** [comment]
issue close 할께요!
