### ISSUE TITLE
docker jupyter notebook 실행 질문

### ISSUE THREAD

**Issue by oliver0922** [deeplearningzerotoall/PyTorch#45]
![캡처](https://user-images.githubusercontent.com/69920975/108783132-3b07e880-75b0-11eb-83c5-74d94b7b154b.PNG)
어찌저찌해서 가이드대로 설치를 했는데 마지막에서 주피터노트북이 실행이 안되네요 ㅠㅠ
저렇게 메시지는 뜨는데 인터넷 페이지가 안뜨고 url그대로 복사해서 붙여넣기해도 안됩니다 왜그런거죠 ㅠㅠㅠ 도와주세요

**Comment by oliver0922** [comment]
@simonjisu 도와주세요 ㅜㅜ

**Comment by NightHasDay** [comment]
저도 같은 증상인데 어떻게 해야될지 ㅠㅠ

**Comment by simonjisu** [comment]
@oliver0922 @NightHasDay 안녕하세요! 바빠서 답변이 조금 늦었네요. 혹시 노트북을 실행시킨 상태에서 인터넷 창에서 http://localhost:8888 (혹은 http://127.0.0.1:8888)로 접속 해보셨나요?

**Comment by oliver0922** [comment]
해결했습니다  뻘짓하고있었네요 감사해요 ㅎㅎ 
-----Original Message-----

**Comment by simonjisu** [comment]
Issue 가 생기면 다시 열어주세요~~
