### ISSUE TITLE
코드 통일작업

### ISSUE THREAD

**Issue by simonjisu** [deeplearningzerotoall/PyTorch#8]
1. 시드 고정 코드 추가
```
# 다른 숫자도 상관없을듯 합니다
torch.manual_seed(777)
np.random.seed(777)
```

2. 파일구조 통일: 여러 방법이 있습니다. (선택이 필요합니다)
    * .py 과 .ipynb 두 가지 버전 중 하나만 만들기
    * .py, .ipynb 둘다 만들기 (TF 팀에서 채택중)

3. criterion(loss_function) 과 optimizer 를 밖으로 꺼낼 것인가? 아니면 모델 안에 내장할 것인가? 

```
# CNN lab-11-3
# define cost/loss & optimizer
self.criterion = torch.nn.CrossEntropyLoss()    # Softmax is internally computed.
self.optimizer = torch.optim.Adam(self.parameters(), lr=learning_rate)
```

```
# CNN lab-09-3
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)  # modify learning rate 0.1 to 1
```

**Comment by dldldlfma** [comment]
github에 올려두니 관심도가 조금 떨어지는 걸까요? ㅠㅠ 카톡방에서 투표를 돌려보고 결과가 나온데로 issue에 공지하고 진행하는 것이 좋을 것 같습니다 :)

**Comment by simonjisu** [comment]
@dldldlfma 그러게요 ㅋㅋ 깃허브 알림이 안갔을 수도 있긴하죠 ㅋㅋ 카톡방으로 한번 물어볼께요
